openapi: 3.0.3
info:
  title: Calculator Service
  description: Service for adding numbers, a Goa teaser
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 1089204046671954241
          format: int64
        example: 3833729960400405184
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 7617773024289378824
          format: int64
        example: 8614350958614154271
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 9092197569596372935
                format: int64
              example: 4285228716133201605
  /div/{a}/{b}:
    get:
      tags:
      - calc
      summary: div calc
      operationId: calc#div
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 1232634558296710584
          format: int64
        example: 2965960569464252933
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 6525775414444532386
          format: int64
        example: 5635247262153220700
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 2937026320033011362
                format: int64
              example: 6595082841550375708
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /openapi.json:
    get:
      tags:
      - calc
      summary: Download ./gen/http/openapi.json
      operationId: calc#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
tags:
- name: calc
  description: The calc service performs operations on numbers.
